### ISSUE TITLE
Issue at server startup

### ISSUE THREAD

**Issue by walker27460** [lightbulblighter/Rboxlo#112]
It seems there is an issue around ciphersweet.
here is my log.
```
rboxlo_database  | 2021-08-13 10:17:50+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.6.4+maria~focal started.
rboxlo_server    | 
rboxlo_server    | > server@1.0.0 start /app
rboxlo_server    | > node index.js
rboxlo_server    | 
rboxlo_database  | 2021-08-13 10:17:50+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
rboxlo_database  | 2021-08-13 10:17:50+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.6.4+maria~focal started.
rboxlo_database  | 2021-08-13 10:17:50 0 [Note] mysqld (server 10.6.4-MariaDB-1:10.6.4+maria~focal) starting as process 1 ...
rboxlo_database  | 2021-08-13 10:17:50 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
rboxlo_database  | 2021-08-13 10:17:50 0 [Note] InnoDB: Number of pools: 1
rboxlo_database  | 2021-08-13 10:17:50 0 [Note] InnoDB: Using ARMv8 crc32 + pmull instructions
rboxlo_database  | 2021-08-13 10:17:50 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
rboxlo_database  | 2021-08-13 10:17:50 0 [Note] InnoDB: Using Linux native AIO
rboxlo_database  | 2021-08-13 10:17:50 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
rboxlo_database  | 2021-08-13 10:17:50 0 [Note] InnoDB: Completed initialization of buffer pool
rboxlo_server    | /app/node_modules/ciphersweet-js/lib/keyprovider/stringprovider.js:25
rboxlo_server    |         buf.copy(this.symmetricKey, 0);
rboxlo_server    |             ^
rboxlo_server    | 
rboxlo_server    | TypeError: Cannot read property 'copy' of undefined
rboxlo_server    |     at new StringProvider (/app/node_modules/ciphersweet-js/lib/keyprovider/stringprovider.js:25:13)
rboxlo_server    |     at Object.<anonymous> (/app/lib/base/locker.js:13:16)
rboxlo_server    |     at Module._compile (internal/modules/cjs/loader.js:1072:14)
rboxlo_server    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
rboxlo_server    |     at Module.load (internal/modules/cjs/loader.js:937:32)
rboxlo_server    |     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
rboxlo_server    |     at Module.require (internal/modules/cjs/loader.js:961:19)
rboxlo_server    |     at require (internal/modules/cjs/helpers.js:92:18)
rboxlo_server    |     at Object.<anonymous> (/app/lib/user.js:13:16)
rboxlo_server    |     at Module._compile (internal/modules/cjs/loader.js:1072:14)
rboxlo_server    | npm ERR! code ELIFECYCLE
rboxlo_server    | npm ERR! errno 1
rboxlo_server    | npm ERR! server@1.0.0 start: `node index.js`
rboxlo_server    | npm ERR! Exit status 1
rboxlo_server    | npm ERR! 
rboxlo_server    | npm ERR! Failed at the server@1.0.0 start script.
rboxlo_server    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
rboxlo_database  | 2021-08-13 10:17:50 0 [Note] InnoDB: 128 rollback segments are active.
rboxlo_database  | 2021-08-13 10:17:50 0 [Note] InnoDB: Creating shared tablespace for temporary tables
rboxlo_database  | 2021-08-13 10:17:50 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
rboxlo_database  | 2021-08-13 10:17:50 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
rboxlo_database  | 2021-08-13 10:17:50 0 [Note] InnoDB: 10.6.4 started; log sequence number 79020; transaction id 72
rboxlo_database  | 2021-08-13 10:17:50 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
rboxlo_database  | 2021-08-13 10:17:50 0 [Note] Plugin 'FEEDBACK' is disabled.
rboxlo_database  | 2021-08-13 10:17:51 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
rboxlo_database  | 2021-08-13 10:17:51 0 [Note] Server socket created on IP: '0.0.0.0'.
rboxlo_database  | 2021-08-13 10:17:51 0 [Note] Server socket created on IP: '::'.
rboxlo_database  | 2021-08-13 10:17:51 0 [Warning] 'proxies_priv' entry '@% root@database' ignored in --skip-name-resolve mode.
rboxlo_database  | 2021-08-13 10:17:51 0 [Note] mysqld: ready for connections.
rboxlo_database  | Version: '10.6.4-MariaDB-1:10.6.4+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
rboxlo_server exited with code 1
rboxlo_database  | 2021-08-13 10:17:51 0 [Note] InnoDB: Buffer pool(s) load completed at 210813 10:17:51
```

**Comment by GlowingUmbreon** [comment]
Make sure you have set all the .env variables correctly.

**Comment by walker27460** [comment]
my .env looks like this
```
PRODUCTION=false
TZ=Asia/Tokyo
NAME=rboxlo
CURRENCY_NAME=rbux
SOCIAL_MEDIA=
VERSION=1.0.0

SERVER_HTTPS=false
SERVER_DOMAIN=rboxlo.loc
SERVER_CLOUDFLARE=false
SERVER_PORT=80
SERVER_SESSION_SECRET=
SERVER_COOKIE_SECRET=

ENCRYPTION_KEY=oZX8VNJDDAo3mOfx8OnCTu3DjSahqf7P
CIPHERSWEET_KEY=

TOOTSIE_PASSWORD=

DB_PASSWORD=Walker27460
DB_USERNAME=root
DB_NAME=rboxlo

PRIVATE_LOCKDOWN=false
PRIVATE_REGISTRATION=true
PRIVATE_REFERRAL=false
PRIVATE_INVITE_ONLY=false
PRIVATE_CLOSED=false

MAIL_PASSWORD=
MAIL_USERNAME=no-reply

GOOGLE_RECAPTCHA_SITE_KEY=
GOOGLE_RECAPTCHA_PRIVATE_KEY=
GOOGLE_RECAPTCHA_ENABLED=false
GOOGLE_ANALYTICS_TAG=
GOOGLE_ANALYTICS_ENABLED=false

STIPEND_TIMEOUT=86400
STIPEND_AMOUNT=25

MAX_PLACE_SIZE=100mb
MAX_ARBITER_SIZE=25mb
MAX_APPLICATION_SIZE=100mb
MAX_LAUNCHER_SIZE=25mb

```

**Comment by GlowingUmbreon** [comment]
The error appears to be from you not setting the `CIPHERSWEET_KEY` correctly, Use this tool https://www.convertstring.com/EncodeDecode/HexEncode and encode the ENCRYPTION_KEY, and make sure if you ever publish it to production make sure to change all the passwords etc. Since you have just sent them here.

**Comment by walker27460** [comment]
Fixed. close this issue.
