### ISSUE TITLE
problem with website?

### ISSUE THREAD

**Issue by TrueDubzy** [lightbulblighter/Rboxlo#78]
sorry me again how do i use the website it looks like nothing loading? im not sure.
![yay](https://user-images.githubusercontent.com/20246342/113447350-9a4bea80-93f1-11eb-87dc-5b648bb8bd51.png)

**Comment by lightbulblighter** [comment]
The thumbnail didn't copy correctly, copy Server/data to Container/Server/data and try registering again

**Comment by TrueDubzy** [comment]
it wont let me permission denied, and can i ask you a few questions after this

**Comment by TrueDubzy** [comment]
i forced copy with root and this happend DubzysLego_database | 2021-04-02T19:47:56.311011Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.23'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
DubzysLego_server | (node:1) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, copyfile '/app/data/thumbnails/users/0.png' -> '/app/data/thumbnails/users/2.png'
DubzysLego_server |     at Object.copyFileSync (fs.js:1991:3)
DubzysLego_server |     at setDefaultThumbnail (/app/websites/eclipse/lib/user.js:335:8)
DubzysLego_server |     at /app/websites/eclipse/lib/user.js:758:40
DubzysLego_server |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
DubzysLego_server | (Use `node --trace-warnings ...` to show where the warning was created)
DubzysLego_server | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
DubzysLego_server | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by TrueDubzy** [comment]
and unrelated to this i dont know how to setup client host games and use admin

**Comment by TrueDubzy** [comment]
im still having the thumbnails error i tried it on my windows pc resetup everything and the same this is the error 

server_1    | Running Rboxlo on port 80
server_1    | (node:1) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, copyfile '/app/data/thumbnails/users/0.png' -> '/app/data/thumbnails/users/1.png'
server_1    |     at Object.copyFileSync (fs.js:1991:3)
server_1    |     at setDefaultThumbnail (/app/websites/eclipse/lib/user.js:335:8)
server_1    |     at /app/websites/eclipse/lib/user.js:758:40
server_1    |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
server_1    | (Use `node --trace-warnings ...` to show where the warning was created)
server_1    | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
server_1    | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by lightbulblighter** [comment]
Does this exist? `/Containers/Server/data/thumbnails/users`, relative to where you're keeping Rboxlo? If not, make sure this exists BEFORE turning on Rboxlo.
![image](https://user-images.githubusercontent.com/59720715/113453339-65c53800-93cb-11eb-8260-2d9fe389b529.png)

**Comment by TrueDubzy** [comment]
![Capture](https://user-images.githubusercontent.com/20246342/113479235-c7e27380-9485-11eb-98e3-a81697197666.PNG)
yes
